完成？
hal-art/HAL-Andr4t pull request #6
Opened 2022-11-17 15:39 UTC by Keno9184

2022-11-17 23:52 UTC, hal-art requested changes
全体的には良いと思う。
申し訳ないけど、細かいところだけ直してほしい。

2022-11-17 23:52 UTC, hal-art commented on main/main.py
> +    if(not(__args_analyze_ip(args) and __args_analyze_port(args))):
1. 数行上でも__args_analyze_ipと__args_analyze_portを呼んでるけど何故？
2. この条件式だとipアドレスとポートの入力が両方共失敗している時しかFalseを返さない。ipアドレス、ポートどちらかが一方でも失敗してたらFalseを返して。

2022-11-17 23:52 UTC, hal-art commented on main/main.py
> +    IP=args.arg2
変数名は小文字かな。複数単語の場合はアンダースコア区切り
apple
apple_number
みたいな

2022-11-17 23:52 UTC, hal-art commented on main/main.py
> +    android = Andr4t(IP,port) #androidはAndr4tのインスタンス
これも小文字ね

2022-11-17 23:52 UTC, hal-art commented on main/main.py
> +
不要な差分(これで言うと空行)は無しでお願いー。
差分は必要最低限のみね

2022-11-17 23:52 UTC, hal-art commented on main/main.py
> +        print("-aを先頭字として入力してください")
ごめん、昨日の打合せでは適当にやったからprintメソッド使ったんだけど、
本来は僕が作ったConsoleモジュールを使ってほしい。
使い方は僕が書いた他のソースファイル見れば分かる。

**print使ってるところは全部同じように置き換えてほしい。**

2022-11-19 08:27 UTC, hal-art requested changes
とりあえずこの指摘したとこだけ直してー。
後は僕の方で少しだけ手直ししてみる。

2022-11-19 08:27 UTC, hal-art commented on main/main.py
> +    if(not args[1] == ARG_IP_ADDRESS_PREFIX):
1は直接書くのではなく定数化してー。

2022-11-19 08:27 UTC, hal-art commented on main/main.py
> +        print('Please enter "-a" as the first character.')
printメソッドは基本使わないこと。
代わりにConsole.printlメソッドを使用すること。

2022-11-19 08:27 UTC, hal-art commented on main/main.py
> +def sys_args():
これはメソッドで書かない方がいい。
プロパティ化してみよう。検索してみて。

2022-11-19 08:27 UTC, hal-art commented on main/main.py
> +    port=int(args[4])
定数化してね

2022-11-19 08:27 UTC, hal-art commented on main/main.py
> +
この差分いらないんじゃね？

2022-11-19 21:02 UTC, Keno9184 commented on main/main.py
> +        print('Please enter "-a" as the first character.')
printlのシグネチャが見つからないってエラーが来る...

2022-11-20 01:30 UTC, merged